version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: yarn
      - run:
          name: release
          command: npm run semantic-release || true
      - run:
          name: test
          command: yarn run test:jest
      - codecov/upload:
          file: coverage/*.json
          flags: frontend
